#!/usr/bin/env python3
"""Serve the static site locally — robustly, with no dependencies.

The pages load their data with `fetch()`, so the site must be served over HTTP;
opening the files from disk (file://) silently breaks data loading. This wrapper
makes that one-command and forgiving:

  * serves the bundled `site/` directory no matter what folder you run it from,
  * falls back to the next free port if the default one is taken,
  * warns (but still serves) when the generated data files are missing.

    python3 serve.py            # http://localhost:8000
    python3 serve.py 9000       # pick a port
    python3 serve.py --open     # also open it in your browser

Stop with Ctrl-C.
"""

from __future__ import annotations

import argparse
import contextlib
import functools
import http.server
import socket
import sys
import webbrowser
from pathlib import Path

SITE_DIR = Path(__file__).resolve().parent / "site"
DEFAULT_PORT = 8000
# Generated by the pipeline; the site degrades gracefully without them, but a
# heads-up saves a confusing "no predictions yet" screen.
DATA_FILES = ["data.json", "worldcup.json", "record.json", "injuries.json"]


def find_open_port(preferred: int, tries: int = 20) -> int:
    """Return `preferred` if free, otherwise the next open port above it."""
    for port in range(preferred, preferred + tries):
        with contextlib.closing(socket.socket(socket.AF_INET, socket.SOCK_STREAM)) as s:
            s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            if s.connect_ex(("127.0.0.1", port)) != 0:
                return port
    raise SystemExit(
        f"No free port found in {preferred}..{preferred + tries - 1}. "
        f"Pass an explicit one, e.g. `python3 serve.py {preferred + 100}`."
    )


def main() -> int:
    parser = argparse.ArgumentParser(description="Serve the Barn Betting Inc. site locally.")
    parser.add_argument("port", nargs="?", type=int, default=DEFAULT_PORT,
                        help=f"preferred port (default {DEFAULT_PORT})")
    parser.add_argument("--open", action="store_true", help="open the site in a browser")
    args = parser.parse_args()

    if not (SITE_DIR / "index.html").is_file():
        raise SystemExit(f"Can't find the site at {SITE_DIR} — is the repo intact?")

    missing = [f for f in DATA_FILES if not (SITE_DIR / f).is_file()]
    if missing:
        print(f"⚠  Missing data files: {', '.join(missing)}")
        print("   Generate them with `python -m agent.pipeline` (and "
              "`python -m agent.worldcup.pipeline`). Serving anyway.\n")

    port = find_open_port(args.port)
    if port != args.port:
        print(f"⚠  Port {args.port} is busy — using {port} instead.")

    url = f"http://localhost:{port}"
    handler = functools.partial(http.server.SimpleHTTPRequestHandler, directory=str(SITE_DIR))
    # ThreadingHTTPServer keeps a slow asset from blocking the parallel JSON fetches.
    with http.server.ThreadingHTTPServer(("", port), handler) as httpd:
        print(f"Serving {SITE_DIR} at {url}  (Ctrl-C to stop)")
        if args.open:
            webbrowser.open(url)
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print("\nStopped.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
